services:
  # PHP-FPM service (Symfony back-end)
  php-fpm:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    environment:
      - APP_ENV=dev # mettre APP_ENV=prod si plus besoin
      - APP_DEBUG=1 # supprimer cette ligne si plus d'usage
    expose:
      - 9000
    networks:
      - default

  # Nginx service (Symfony back-end)
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
    ports:
      - "80:80"
    depends_on:
      - php-fpm
    networks:
      - default

  # PostgreSQL service
  db:
    image: postgres:14
    container_name: symfony-db
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: ilovecake
      POSTGRES_DB: symfony
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default

  # Next.js service (front-end)
  nextjs:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/app  # Enable it in dev mode
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - db    # If Next.js needs data from the database or API, you can make it depend on db or php-fpm
    networks:
      - default

# Volume for PostgreSQL database data persistence
volumes:
  pgdata:

networks:
  default:
    #name: symfony-app # Use this if you want to specify the network name
    driver: bridge